twig:
    globals:
        label_bogart_front_group: '%env(LABEL_BOGART_FRONT_GROUP)%'
        label_bogart_front_key: '%env(LABEL_BOGART_FRONT_KEY)%'
        label_bogart_body_group: '%env(LABEL_BOGART_BODY_GROUP)%'
        label_bogart_body_key: '%env(LABEL_BOGART_BODY_KEY)%'