services:
    nginx:
        image: nginx:stable-alpine
        ports:
            - "443:443"
        volumes:
            - ./.docker/nginx.prod.conf:/etc/nginx/conf.d/default.conf:ro
            - ./.docker/ssl:/etc/nginx/ssl

    php:
        environment:
            APP_ENV: prod
            APP_DEBUG: 0
            PIMCORE_DEV_MODE: false