site_name: Pimcore Megstyl
site_url: https://pim.megstyl.com/
repo_url: https://github.com/bambooooooo/
nav:
    - Wprowadzenie: index.md
    - Instrukcja użytkownika:
        - Zarządzanie produktami (PIM): guides/pim.md
        - Zarządzanie zasobami cyfrowymi (DAM): guides/dam.md
        - Feedy produktowe: guides/feeds.md
        - Proces produkcyjny: guides/man.md
        - Skróty klawiszowe: guides/shortcuts.md
        - Dodatki (różne): guides/addons.md
        - Zgłaszanie błędów: guides/errors.md
    - Architektura systemu:
        - Hosting: architecture/hosting.md
    - Integracje:
        - SubiektGT: integrations/subiekt_gt.md
        - Baselinker: integrations/baselinker.md
        - GS1: integrations/gs1.md
        - Prestashop: integrations/prestashop.md
        - Allegro: integrations/allegro.md
        - DeepL: integrations/deepl.md
        - Google: integrations/google.md
        - Optimik 3: integrations/optimik3.md
        - Feedy: integrations/feeds.md
        - Stany magazynowe: integrations/stocks.md
    - Dokumentacja techniczna:
        - Definicje klas: techdocs/class_definitions.md
        - Development: techdocs/development.md
        - Konwencje: techdocs/conventions.md
    - Nowe propozycje: todo.md
theme:
    name: material
    primary: black
    logo: https://sklep.megstyl.pl/themes/megtheme/assets/img/logo.svg
    palette:
        # Palette toggle for light mode
        - scheme: default
          primary: white
          toggle:
              icon: material/brightness-7
              name: Switch to dark mode

        # Palette toggle for dark mode
        - scheme: slate
          primary: white
          toggle:
              icon: material/brightness-4
              name: Switch to light mode


