pimcore:
    assets:
        image:
            thumbnails:
                definitions:
                    webp:
                        items: {  }
                        medias: {  }
                        name: webp
                        description: ''
                        group: ''
                        format: SOURCE
                        quality: 85
                        highResolution: null
                        preserveColor: false
                        preserveMetaData: false
                        rasterizeSVG: false
                        downloadable: false
                        modificationDate: 1750941552
                        creationDate: 1750941541
                        preserveAnimation: false
