pimcore:
    assets:
        image:
            thumbnails:
                definitions:
                    webp_1400:
                        items:
                            -
                                method: scaleByHeight
                                arguments:
                                    height: 1400
                                    forceResize: true
                        medias: {  }
                        name: webp_1400
                        description: ''
                        group: ''
                        format: SOURCE
                        quality: 90
                        highResolution: null
                        preserveColor: false
                        preserveMetaData: false
                        rasterizeSVG: false
                        downloadable: false
                        modificationDate: 1751010794
                        creationDate: 1751010093
                        preserveAnimation: false
