pimcore:
    objects:
        select_options:
            definitions:
                ChipboardBorderThickness:
                    id: ChipboardBorderThickness
                    group: ''
                    useTraits: ''
                    implementsInterfaces: ''
                    selectOptions:
                        -
                            value: '0.4'
                            label: '0.4'
                            name: mm04
                        -
                            value: '0.5'
                            label: '0.5'
                            name: mm05
                        -
                            value: '0.6'
                            label: '0.6'
                            name: mm06
                        -
                            value: '0.8'
                            label: '0.8'
                            name: mm08
                        -
                            value: '1.0'
                            label: '1.0'
                            name: mm10
                        -
                            value: '1.3'
                            label: '1.3'
                            name: mm13
                        -
                            value: '2.0'
                            label: '2.0'
                            name: mm20
