pimcore:
    perspectives:
        definitions:
            PIM:
                icon: /bundles/pimcoreadmin/img/flat-color-icons/pimcore-sign.svg
                elementTree:
                    -
                        name: 'Data Obiects'
                        type: objects
                        position: left
                        sort: 0
                        expanded: true
                    -
                        name: 'Assets'
                        type: assets
                        position: left
                        sort: 1
                        expanded: false
                    -
                        name: 'Documents'
                        type: documents
                        position: left
                        sort: 2
                        expanded: true
                        
            Sets:
                icon: /UI/4-squares-red.svg
                toolbar:
                    file:
                        items:
                            dashboards: false
                            openDocument: false
                            openAsset: false
                            searchReplace: false
                            seemode: false
                            help: false
                            about: false
                    settings:
                        hidden: true
                    extras:
                        hidden: true
                    datahub:
                        hidden: true

                elementTree:
                    -
                        type: customview
                        position: left
                        id: sets
                        sort: 0
                        expanded: true
                    -
                        type: customview
                        position: right
                        id: products_read_only
                        sort: 0
                        expanded: true
            Packages:
                icon: /bundles/pimcoreadmin/img/flat-color-icons/deployment.svg
                elementTree:
                    -
                        name: 'Products'
                        type: customview
                        position: left
                        id: products_read_only
                        expanded: true
                        sort: 1
                    -
                        name: 'Packages'
                        type: customview
                        position: right
                        id: packages_read_only
                        expanded: true
                        sort: 1
                    -
                        name: 'Users'
                        type: customview
                        position: right
                        id: users_read_only
                        expanded: false
                        sort: 2
                    -
                        name: 'Carriers'
                        type: customview
                        position: right
                        id: load_carriers_readonly
                        expanded: false
                        sort: 3
            Orders:
                icon: /bundles/pimcoreadmin/img/flat-color-icons/shopping-cart.svg
                toolbar:
                    file:
                        items:
                            dashboards: false
                            openDocument: false
                            openAsset: false
                            searchReplace: false
                            seemode: false
                            help: false
                            about: false
                    settings:
                        hidden: true
                    marketing:
                        hidden: true
                    extras:
                        hidden: true
                    datahub:
                        hidden: true
                    search:
                        items:
                            quickSearch: false
                            documents: false
                            assets: false
                            objects: true
                elementTree:
                    -
                        name: 'Production'
                        type: customview
                        position: left
                        id: orders
                        sort: 0
                        expanded: true
                    -
                        name: 'Products'
                        type: customview
                        position: right
                        id: products_read_only
                        expanded: true
                        sort: 0
                    -
                        name: 'Users'
                        type: customview
                        position: right
                        id: users_read_only
                        expanded: false
                        sort: 1
                    -
                        name: 'Carriers'
                        type: customview
                        position: right
                        id: load_carriers_readonly
                        expanded: false
                        sort: 2
