pimcore:
    perspectives:
        definitions:
            PIM:
                icon: /bundles/pimcoreadmin/img/flat-color-icons/pimcore-sign.svg
                elementTree:
                    -
                        name: 'Data Obiects'
                        type: objects
                        position: left
                        sort: 0
                        expanded: true
                    -
                        name: 'Assets'
                        type: assets
                        position: left
                        sort: 1
                        expanded: false
                    -
                        name: 'Documents'
                        type: documents
                        position: left
                        sort: 2
                        expanded: true