pimcore_custom_reports:
    definitions:
        product_missing_descriptions:
            name: product_missing_descriptions
            sql: ''
            dataSourceConfig:
                -
                    sql: "p.Name as Nazwa,\np.ooo_id as Id"
                    from: 'object_localized_query_Product_pl p'
                    where: ''
                    groupby: ''
                    orderby: ''
                    orderbydir: null
                    type: sql
            columnConfiguration:
                -
                    name: Nazwa
                    display: true
                    export: true
                    order: true
                    width: ''
                    label: ''
                    id: extModel1294-3
                -
                    name: Id
                    display: true
                    export: true
                    order: true
                    width: ''
                    label: ''
                    columnAction: openObject
                    id: extModel1294-4
            niceName: 'Brakujące opisy produktów'
            group: ''
            groupIconClass: ''
            iconClass: ''
            menuShortcut: true
            reportClass: ''
            chartType: ''
            pieColumn: null
            pieLabelColumn: null
            xAxis: ooo_id
            yAxis:
                - uzupelnione
            modificationDate: 1756108131
            creationDate: 1756106716
            shareGlobally: true
            sharedUserNames: {  }
            sharedRoleNames: {  }
