name: Symfony production deployment

on:
    push:
        branches:
            - main

jobs:
    deploy:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Deploy using SSH
              uses: appleboy/ssh-action@master
              with:
                  host: ${{ secrets.SSH_HOST }}
                  username: ${{ secrets.SSH_USER }}
                  key: ${{ secrets.SSH_PRIVATE_KEY }}
                  port: ${{ secrets.SSH_PORT }}
                  passphrase: ${{ secrets.SSH_PASSPHRASE }}
                  script: |
                      cd ~/pimcore-test/pimcore
                      git pull origin master
                      git checkout master
                      git log -n 1 --pretty='format:%h'
                      docker compose exec php bin/console pimcore:maintenance-mode --ignore-maintenance-mode --enable
                      docker compose exec php bin/console pimcore:deployment:classes-rebuild --ignore:maintenance-mode
                      docker compose exec php bin/console pimcore:maintenance-mode --ignore-maintenance-mode --disable
